[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2024"

[dependencies]
cached = "0.55.1"
glam = "0.30.4"
hashable = "0.0.0"
itertools = "0.14.0"
nom = "8.0.0"
pathfinding = "4.14.0"
rayon = "1.10.0"
regex = "1.11.1"
